name: CI/CD with tag injection

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: DevOps_Mini_1

    steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - name: Set Docker tag from commit
      id: vars
      run: echo "TAG=sha-${GITHUB_SHA::7}" >> $GITHUB_ENV

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build & Push Docker Image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: dockerdu2914/nginx:${{ env.TAG }}

    - name: Install yq
      run: sudo snap install yq

    - name: Update image tag in values.yaml
      run: |
        yq e -i '.image.tag = "${{ env.TAG }}"' nginx-chart/values-dev.yaml
        yq e -i '.image.tag = "${{ env.TAG }}"' nginx-chart/values-staging.yaml
        yq e -i '.image.tag = "${{ env.TAG }}"' nginx-chart/values-prod.yaml

    - name: Commit updated values.yaml files
      run: |
        git config user.name "ci-bot"
        git config user.email "ci@bot.local"
        git add nginx-chart/values-*.yaml
        git commit -m "CI: Update image tag to ${{ env.TAG }}"
        git push origin main
